updated gitignore and husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -33,5 +33,9 @@ npm run build ||
     false;
 )
 
+npm run add-build || {
+    echo 'Failed adding build. Please try again'
+}
+
 # If everything passes... Now we can commit
 echo 'Everything looks good! Committing changes!'
